### ISSUE TITLE
ownCloud upload sends a 0 byte file 

### ISSUE THREAD

**Issue by paultranvan** [Decentralized-Sharing-Working-Group/server-to-server#15]
When sending a file to an owncloud server, an err: null is received; the uploaded file is present on the owncloud server but has a 0 byte size

**Comment by michielbdejong** [comment]
hm, works for me. Are you using the curl example from the readme? I just checked on https://owncloud.michielbdejong.com/index.php/apps/files/ (log in with ohyuH8Eipie1choo5shaisheezaiSoh2atouf3aa / ahCe1oaboh2aephoo5kahghaen9leaQuai0zooki ), the files are there, have size 355 Kb, and if you dowload them you see the image again.

Are you using ownCloud 8?

**Comment by michielbdejong** [comment]
Ah, I think I know what happened - were you using the web form? And if so, did you click 'Browse...' on the left before clicking 'Submit'?
![screenshot from 2015-03-26 18 03 00](https://cloud.githubusercontent.com/assets/408412/6851978/671e03a8-d3e2-11e4-8231-6a15e1428a34.png)

**Comment by paultranvan** [comment]
Yes I did. Do you mean that the file could have been in the cache?

**Comment by michielbdejong** [comment]
Let's debug via irc!

**Comment by michielbdejong** [comment]
@Gara64 please reopen if that did not fix it!

**Comment by paultranvan** [comment]
It didn't fix the issue, tested with owncloud 7 and owncloud 8, one with self-signed certificate, the other without TLS. I checked with a webdav client, everything's fine.
In both cases, the base path contains the owncloud directory, e.g. https://gara.ovh/owncloud/ 
Could it be somehow related ?

**Comment by michielbdejong** [comment]
I don't know, can you create test accounts for me on those servers where it fails?

Everything is working fine when you use https://server-to-server.michielbdejong.com:8123/ and https://owncloud.michielbdejong.com/, right?
