### ISSUE TITLE
Cozy curl example stopped working?

### ISSUE THREAD

**Issue by michielbdejong** [Decentralized-Sharing-Working-Group/server-to-server#9]
It seems [the curl example](https://github.com/Decentralized-Sharing-Working-Group/server-to-server/blob/master/doc/curl-examples.md#to-send-this-file-to-a-cozy-server) stopped working, it's now responding with a 401 header.

cc @Gara64

**Comment by paultranvan** [comment]
Yes, I figured out the problem, probably an update on the proxy that overwrote the hack to access couchdb remotely. I will fix it tomorrow

**Comment by paultranvan** [comment]
It's working again

**Comment by michielbdejong** [comment]
Great!
